name: linkShepherdServer
version: 0.0.1
description: A sample command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http_server: any
  postgresql: any
  shelf: any
  shelf_exception_response: any
  shelf_route: any
  shelf_static: any
  shelf_auth: any
  linkShepherdClient:
    path: C:\Users\Lukasz\dart\linkShepherdClient
dev_dependencies:
  unittest: any
