name: linkShepherdServer
version: 0.0.1
description: A sample command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http_server: any
  postgresql: any
dev_dependencies:
  unittest: any
